import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import { ConfirmDialogProvider, fontVariables } from '@/shared/ui-kit';
import '@/shared/ui-kit/styles/tokens.scss';
import '@/app/styles/globals.css';

type RootLayoutProps = Readonly<{
    children: ReactNode;
}>;

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({ children }: RootLayoutProps) => (
    <html lang="en" className={fontVariables}>
        <body>
            {children}

            <Toaster
                position="top-center"
                theme="dark"
                richColors
            />

            <ConfirmDialogProvider />
        </body>
    </html>
);

export default RootLayout;
